### 사용자 정보 조회
GET http://localhost:8080/api/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhY2Nlc3MtdG9rZW4iLCJyb2xlcyI6IlJPTEVfVVNFUiIsInVzZXJJZCI6InRlc3QxMjM0QGdtYWlsLmNvbSIsImlhdCI6MTcwNzQ4NDM5MywiZXhwIjoxNzA3NDg2MTkzfQ.09Z5Cn1U4PN963NnoEoMxEyxaO8nVH9sQBFzyos_f5k


### 사용자 정보 수정
PUT http://localhost:8080/api/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhY2Nlc3MtdG9rZW4iLCJyb2xlcyI6IlJPTEVfVVNFUiIsInVzZXJJZCI6InRlc3QxMjM0QGdtYWlsLmNvbSIsImlhdCI6MTcwNzQ4NDM5MywiZXhwIjoxNzA3NDg2MTkzfQ.09Z5Cn1U4PN963NnoEoMxEyxaO8nVH9sQBFzyos_f5k

{
  "password": "1234512",
  "nickname": "abcd12",
  "phoneNumber": "010-1111-5678"
}