spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:33062/movieMate?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: s5554549

  jpa:
    hibernate:
      ddl-auto:  create-drop    # create, create_drop, update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database: mysql
    defer-datasource-initialization: true