spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:33062/movieMate?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: s5554549

  jpa:
    hibernate:
      ddl-auto:  create-drop    # create, create_drop, update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database: mysql
    defer-datasource-initialization: true

  profiles:
    active: prod

  data:
    redis:
      host: localhost
      port: 6379

  jwt:
    header: Authorization
    prefix: "Bearer "
    secret: bW92aWVNYXRlLXNwcmluZy1ib290LXByb2plY3Qtand0LXNlY3JldC1rZXkK
    access-token-expire-time: 1800000 # 30분 밀리초
    refresh-token-expire-time: 432000000 # 5일 밀리초